spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecommerce
    username: root
<<<<<<< HEAD
    password: qwerty
=======
    password: Ruuta88!
>>>>>>> e894229a1b70d010868b67bb0b65c6d545e3c544
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always


  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

authframework:
  jwt:
    hskey: KTlgvPcXbnLoYl6b5Ma1oG294dGoZ+fyxBqJiBjQjVo=
    audience: testaudience
    token-ttl: 86400000
