spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecommerce
    username: root
<<<<<<< HEAD
    password: qwerty
=======
<<<<<<< HEAD
    password: aSSolo56*
=======
    password: Ruuta88!
>>>>>>> e2fa2ddb790d98dc48e3b9a9117a96dd43b46970
>>>>>>> 23e1c8d46ff5d0e0e5ebecbe8521ebacbe78ce27
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always


  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

authframework:
  jwt:
    hskey: KTlgvPcXbnLoYl6b5Ma1oG294dGoZ+fyxBqJiBjQjVo=
    audience: testaudience
    token-ttl: 86400000
